<?php

namespace console\controllers\seeder;

class CountrySeederController extends BaseSeederController
{
    public function actionRun()
    {
        $data = [
            [
                "id" => 35,
                "name_ru" => "Европа",
                "name_uz" => "Evropa",
                "name_en" => "Europe",
                "schengen" => false,
                "parent_id" => null,
                "code" => null,
                "image" => "35.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 49,
                "name_ru" => "Азия",
                "name_uz" => "Osiyo",
                "name_en" => "Asia",
                "schengen" => false,
                "parent_id" => null,
                "code" => null,
                "image" => null,
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 50,
                "name_ru" => "Америка",
                "name_uz" => "Amerika",
                "name_en" => "America",
                "schengen" => false,
                "parent_id" => null,
                "code" => null,
                "image" => null,
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 51,
                "name_ru" => "СНГ",
                "name_uz" => "MDH",
                "name_en" => "CIS",
                "schengen" => false,
                "parent_id" => null,
                "code" => null,
                "image" => null,
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 53,
                "name_ru" => "Турзона",
                "name_uz" => "Turzona",
                "name_en" => "Tour zone",
                "schengen" => false,
                "parent_id" => null,
                "code" => null,
                "image" => null,
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 55,
                "name_ru" => "Австралия",
                "name_uz" => "Avstraliya",
                "name_en" => "Australia",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "AU",
                "image" => "55.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 73,
                "name_ru" => "Португалия",
                "name_uz" => "Portugaliya",
                "name_en" => "Portugal",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "PT",
                "image" => "73.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 75,
                "name_ru" => "Россия",
                "name_uz" => "Rossiya",
                "name_en" => "Russia",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "RU",
                "image" => "75.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 77,
                "name_ru" => "Румыния",
                "name_uz" => "Ruminiya",
                "name_en" => "Romania",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "RO",
                "image" => "77.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 78,
                "name_ru" => "Бермудские острова",
                "name_uz" => "Bermuda orollari",
                "name_en" => "Bermuda",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "BM",
                "image" => "78.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 114,
                "name_ru" => "Украина",
                "name_uz" => "Ukraina",
                "name_en" => "Ukraine",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "UA",
                "image" => "114.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 82,
                "name_ru" => "Великобритания",
                "name_uz" => "Buyuk Britaniya",
                "name_en" => "United Kingdom of Great Britain",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "GB",
                "image" => "82.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 80,
                "name_ru" => "Босния и Герцеговина	",
                "name_uz" => "Bosniya va Gertsogoviniya	",
                "name_en" => "Bosnia and Herzegovina	",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "BA",
                "image" => "80.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 88,
                "name_ru" => "Сейшелы",
                "name_uz" => "Seyshel orollari",
                "name_en" => "Seychelles islands",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "SC",
                "image" => "88.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 81,
                "name_ru" => "Бразилия",
                "name_uz" => "Braziliya",
                "name_en" => "Brazil",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "BR",
                "image" => "81.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 66,
                "name_ru" => "Аргентина",
                "name_uz" => "Argentina",
                "name_en" => "Argentina",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "AR",
                "image" => "66.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 65,
                "name_ru" => "Оман",
                "name_uz" => "Ummon",
                "name_en" => "Oman",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "OM",
                "image" => "65.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 60,
                "name_ru" => "Албания",
                "name_uz" => "Albaniya",
                "name_en" => "Albania",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "AL",
                "image" => "60.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 59,
                "name_ru" => "Монако",
                "name_uz" => "Monako",
                "name_en" => "Monaco",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "MC",
                "image" => "59.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 90,
                "name_ru" => "Германия",
                "name_uz" => "Germaniya",
                "name_en" => "Germany",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "DE",
                "image" => "90.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 96,
                "name_ru" => "Голландия",
                "name_uz" => "Gollandiya",
                "name_en" => "Netherlands",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "NL",
                "image" => "96.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 64,
                "name_ru" => "Андорра",
                "name_uz" => "Andorra",
                "name_en" => "Andorra",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "AD",
                "image" => "64.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 56,
                "name_ru" => "Австрия",
                "name_uz" => "Avstriya",
                "name_en" => "Austria",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "AT",
                "image" => "56.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 62,
                "name_ru" => "Алжир",
                "name_uz" => "Aljir",
                "name_en" => "Algeria",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "DZ",
                "image" => "62.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 79,
                "name_ru" => "Болгария",
                "name_uz" => "Bolgariya",
                "name_en" => "Bulgaria",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "BG",
                "image" => "79.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 84,
                "name_ru" => "Вьетнам",
                "name_uz" => "Vetnam",
                "name_en" => "Vietnam",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "VN",
                "image" => "84.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 85,
                "name_ru" => "Гвинея",
                "name_uz" => "Gvineya",
                "name_en" => "Guinea",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "GN",
                "image" => "85.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 98,
                "name_ru" => "Гонконг",
                "name_uz" => "Gonkong",
                "name_en" => "Hong Kong	",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "HK",
                "image" => "98.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 89,
                "name_ru" => "Сербия",
                "name_uz" => "Serbiya",
                "name_en" => "Serbia",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "RS",
                "image" => "89.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 133,
                "name_ru" => "Куба",
                "name_uz" => "Kuba",
                "name_en" => "Cuba",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "CU",
                "image" => "133.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 91,
                "name_ru" => "Сингапур",
                "name_uz" => "Singapur",
                "name_en" => "Singapore",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "SG",
                "image" => "91.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 92,
                "name_ru" => "Сирия",
                "name_uz" => "Suriya",
                "name_en" => "Syria",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "SY",
                "image" => "92.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 69,
                "name_ru" => "Перу",
                "name_uz" => "Peru",
                "name_en" => "Peru",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "PE",
                "image" => "69.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 93,
                "name_ru" => "Словакия",
                "name_uz" => "Slovakiya",
                "name_en" => "Slovakia",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "SK",
                "image" => "93.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 94,
                "name_ru" => "Словения",
                "name_uz" => "Sloveniya",
                "name_en" => "Slovenia",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "SI",
                "image" => "94.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 102,
                "name_ru" => "Тайвань",
                "name_uz" => "Tayvan",
                "name_en" => "Taiwan",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "TW",
                "image" => "102.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 83,
                "name_ru" => "Венгрия",
                "name_uz" => "Vengriya	",
                "name_en" => "Hungary",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "HU",
                "image" => "83.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 100,
                "name_ru" => "Греция",
                "name_uz" => "Gretsiya",
                "name_en" => "Greece",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "GR",
                "image" => "100.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 58,
                "name_ru" => "Азербайджан",
                "name_uz" => "Ozarbayjon",
                "name_en" => "Azerbaijan",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "AZ",
                "image" => "58.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 103,
                "name_ru" => "Тунис",
                "name_uz" => "Tunis",
                "name_en" => "Tunisia",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "TN",
                "image" => "103.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 101,
                "name_ru" => "Грузия",
                "name_uz" => "Gruziya",
                "name_en" => "Georgia",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "GE",
                "image" => "101.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 97,
                "name_ru" => "Таджикистан",
                "name_uz" => "Todjikiston",
                "name_en" => "Tajikistan",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "TJ",
                "image" => "97.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 104,
                "name_ru" => "Дания",
                "name_uz" => "Daniya",
                "name_en" => "Denmark",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "DK",
                "image" => "104.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 106,
                "name_ru" => "Доминиканская Республика",
                "name_uz" => "Dominikan Respublikasi",
                "name_en" => "Dominican Republic",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "DO",
                "image" => "106.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 105,
                "name_ru" => "Туркменистан",
                "name_uz" => "Turkmaniston",
                "name_en" => "Turkmenistan",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "TM",
                "image" => "105.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 111,
                "name_ru" => "Индонезия",
                "name_uz" => "Indoneziya",
                "name_en" => "Indonesia",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "ID",
                "image" => "111.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 112,
                "name_ru" => "Иордания ",
                "name_uz" => "Iyordaniya",
                "name_en" => "Jordan",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "JO",
                "image" => "112.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 120,
                "name_ru" => "Ирландия",
                "name_uz" => "Irlandiya",
                "name_en" => "Ireland",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "IE",
                "image" => "120.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 115,
                "name_ru" => "Филиппины",
                "name_uz" => "Filippin",
                "name_en" => "Philippines",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "PH",
                "image" => "115.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 129,
                "name_ru" => "Китай",
                "name_uz" => "Xitoy",
                "name_en" => "China",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "CN",
                "image" => "129.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 121,
                "name_ru" => "Испания",
                "name_uz" => "Ispaniya",
                "name_en" => "Spain",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "ES",
                "image" => "121.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 108,
                "name_ru" => "Израиль",
                "name_uz" => "Isroil",
                "name_en" => "Israel",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "IL",
                "image" => "108.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 124,
                "name_ru" => "Камбоджа",
                "name_uz" => "Kambodjiya",
                "name_en" => "Cambodia",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "KH",
                "image" => "124.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 116,
                "name_ru" => "Финляндия",
                "name_uz" => "Finlandiya",
                "name_en" => "Finland",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "FI",
                "image" => "116.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 117,
                "name_ru" => "Франция",
                "name_uz" => "Frantsiya",
                "name_en" => "France",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "FR",
                "image" => "117.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 119,
                "name_ru" => "Хорватия",
                "name_uz" => "Xorvatiya",
                "name_en" => "Croatia",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "HR",
                "image" => "119.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 130,
                "name_ru" => "Черногория",
                "name_uz" => "Chernogoriya",
                "name_en" => "Montenegro",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "ME",
                "image" => "130.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 125,
                "name_ru" => "Канада",
                "name_uz" => "Kanada",
                "name_en" => "Canada",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "CA",
                "image" => "125.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 126,
                "name_ru" => "Катар",
                "name_uz" => "Qatar",
                "name_en" => "Qatar",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "QA",
                "image" => "126.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 127,
                "name_ru" => "Кипр",
                "name_uz" => "Kipr",
                "name_en" => "Cyprus",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "CY",
                "image" => "127.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 131,
                "name_ru" => "Конго",
                "name_uz" => "Kongo",
                "name_en" => "Congo",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "CG",
                "image" => "131.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 128,
                "name_ru" => "Киргизия",
                "name_uz" => "Qirg'iziston",
                "name_en" => "Kyrgyzstan",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "KG",
                "image" => "128.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 87,
                "name_ru" => "Северная Корея",
                "name_uz" => "Shimoliy Koreya",
                "name_en" => "North Korea",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "KP",
                "image" => "87.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 134,
                "name_ru" => "Кувейт",
                "name_uz" => "Quvayt",
                "name_en" => "Kuwait",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "KW",
                "image" => "134.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 118,
                "name_ru" => "Иран",
                "name_uz" => "Eron",
                "name_en" => "Iran",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "IR",
                "image" => "118.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 132,
                "name_ru" => "Чехия",
                "name_uz" => "Chexiya",
                "name_en" => "Czech Republic",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "CZ",
                "image" => "132.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 136,
                "name_ru" => "Литва",
                "name_uz" => "Litva",
                "name_en" => "Lithuania",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "LT",
                "image" => "136.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 57,
                "name_ru" => "Молдавия, Молдова",
                "name_uz" => "Moldova",
                "name_en" => "Moldavia, Moldova",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "MD",
                "image" => "57.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 74,
                "name_ru" => "Белоруссия",
                "name_uz" => "Belarusiya",
                "name_en" => "Belarus",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "BY",
                "image" => "74.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 163,
                "name_ru" => "Судан",
                "name_uz" => "Sudan",
                "name_en" => "Sudan",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "SD",
                "image" => "163.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 167,
                "name_ru" => "Самоа",
                "name_uz" => "Samoa",
                "name_en" => "Samoa",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "WS",
                "image" => "167.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 68,
                "name_ru" => "Армения",
                "name_uz" => "Armeniya",
                "name_en" => "Armenia",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "AM",
                "image" => "68.png",
                "order" => null,
                "kapital_id" => 122
            ],
            [
                "id" => 109,
                "name_ru" => "Турция",
                "name_uz" => "Turkiya",
                "name_en" => "Turkey",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "TR",
                "image" => "109.png",
                "order" => null,
                "kapital_id" => 217
            ],
            [
                "id" => 107,
                "name_ru" => "Египет",
                "name_uz" => "Misr",
                "name_en" => "Egypt",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "EG",
                "image" => "107.png",
                "order" => null,
                "kapital_id" => 8
            ],
            [
                "id" => 70,
                "name_ru" => "Афганистан",
                "name_uz" => "Afg'oniston",
                "name_en" => "Afghanistan",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "AF",
                "image" => "70.png",
                "order" => null,
                "kapital_id" => 53
            ],
            [
                "id" => 67,
                "name_ru" => "Пакистан",
                "name_uz" => "Pokiston",
                "name_en" => "Pakistan",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "PK",
                "image" => "67.png",
                "order" => null,
                "kapital_id" => 52
            ],
            [
                "id" => 72,
                "name_ru" => "Бахрейн",
                "name_uz" => "Bahrayn",
                "name_en" => "Bahrain",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "BH",
                "image" => "72.png",
                "order" => null,
                "kapital_id" => 30
            ],
            [
                "id" => 123,
                "name_ru" => "Казахстан",
                "name_uz" => "Qozog'iston",
                "name_en" => "Kazakhstan",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "KZ",
                "image" => "123.png",
                "order" => null,
                "kapital_id" => 146
            ],
            [
                "id" => 99,
                "name_ru" => "Таиланд",
                "name_uz" => "Tailand",
                "name_en" => "Thailand",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "TH",
                "image" => "99.png",
                "order" => null,
                "kapital_id" => 74
            ],
            [
                "id" => 135,
                "name_ru" => "Латвия",
                "name_uz" => "Latviya	",
                "name_en" => "Latvia",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "LV",
                "image" => "135.png",
                "order" => null,
                "kapital_id" => 78
            ],
            [
                "id" => 110,
                "name_ru" => "Индия",
                "name_uz" => "Hindiston",
                "name_en" => "India",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "IN",
                "image" => "110.png",
                "order" => null,
                "kapital_id" => 141
            ],
            [
                "id" => 71,
                "name_ru" => "Польша",
                "name_uz" => "Polsha",
                "name_en" => "Poland",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "PL",
                "image" => "71.png",
                "order" => null,
                "kapital_id" => 169
            ],
            [
                "id" => 76,
                "name_ru" => "Бельгия",
                "name_uz" => "Belgiya",
                "name_en" => "Belgium",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "BE",
                "image" => "76.png",
                "order" => null,
                "kapital_id" => 63
            ],
            [
                "id" => 143,
                "name_ru" => "Мавритания",
                "name_uz" => "Mavritaniya",
                "name_en" => "Mauritania",
                "schengen" => false,
                "parent_id" => 51,
                "code" => null,
                "image" => "143.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 165,
                "name_ru" => "Кирибати",
                "name_uz" => "Kiribati",
                "name_en" => "Kiribati",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "KI",
                "image" => "165.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 138,
                "name_ru" => "Лихтенштейн",
                "name_uz" => "Lixtenshteyn",
                "name_en" => "Liechtenstein",
                "schengen" => true,
                "parent_id" => 35,
                "code" => null,
                "image" => "138.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 169,
                "name_ru" => "Ангола",
                "name_uz" => "Angola",
                "name_en" => "Angola",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "AO",
                "image" => "169.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 140,
                "name_ru" => "Шенгенская зона",
                "name_uz" => "Shengen hududi",
                "name_en" => "Schengen",
                "schengen" => true,
                "parent_id" => 35,
                "code" => null,
                "image" => "140.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 171,
                "name_ru" => "Папуа - Новая Гвинея",
                "name_uz" => "Papua-Yangi Gvineya",
                "name_en" => "Papua New Guinea",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "PG",
                "image" => "171.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 139,
                "name_ru" => "Люксембург",
                "name_uz" => "Lyuksemburg",
                "name_en" => "Luxembourg",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "LU",
                "image" => "139.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 141,
                "name_ru" => "Маврикий",
                "name_uz" => "Mavrikiy",
                "name_en" => "Mauritius",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "MU",
                "image" => "141.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 137,
                "name_ru" => "Швеция",
                "name_uz" => "Shvetsiya",
                "name_en" => "Sweden",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "SE",
                "image" => "137.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 142,
                "name_ru" => "Шри-Ланка",
                "name_uz" => "Shri-Lanka",
                "name_en" => "Sri-Lanka",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "LK",
                "image" => "142.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 173,
                "name_ru" => "Гана",
                "name_uz" => "Gana",
                "name_en" => "Ghana",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "GH",
                "image" => "173.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 175,
                "name_ru" => "Швейцария",
                "name_uz" => "Shveytsariya",
                "name_en" => "Switzerland",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "CH",
                "image" => "175.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 177,
                "name_ru" => "Намибия",
                "name_uz" => "Namibiya",
                "name_en" => "Namibia",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "NA",
                "image" => "177.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 179,
                "name_ru" => "Исландия",
                "name_uz" => "Islandiya",
                "name_en" => "Iceland",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "IS",
                "image" => "179.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 181,
                "name_ru" => "Соломоновы острова",
                "name_uz" => "Sulaymon orollari",
                "name_en" => "Solomon Islands",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "SB",
                "image" => "181.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 183,
                "name_ru" => "Парагвай",
                "name_uz" => "Paragvay",
                "name_en" => "Paraguay",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "PY",
                "image" => "183.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 185,
                "name_ru" => "Гайана",
                "name_uz" => "Gayana",
                "name_en" => "Guyana",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "GY",
                "image" => "185.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 187,
                "name_ru" => "Мадагаскар",
                "name_uz" => "Madagaskar",
                "name_en" => "Madagascar",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "MG",
                "image" => "187.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 189,
                "name_ru" => "Джибути",
                "name_uz" => "Jibuti",
                "name_en" => "Djibouti",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "DJ",
                "image" => "189.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 191,
                "name_ru" => "Коморские острова",
                "name_uz" => "Komor",
                "name_en" => "Comoros",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "KM",
                "image" => "191.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 193,
                "name_ru" => "Габон",
                "name_uz" => "Gabon",
                "name_en" => "Gabon",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "GA",
                "image" => "193.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 195,
                "name_ru" => "Мьянма",
                "name_uz" => "Myanma",
                "name_en" => "Myanmar",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "MM",
                "image" => "195.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 197,
                "name_ru" => "Мозамбик",
                "name_uz" => "Mozambik",
                "name_en" => "Mozambique",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "MZ",
                "image" => "197.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 199,
                "name_ru" => "Антигуа и Барбуда",
                "name_uz" => "Antigua va Barbuda",
                "name_en" => "Antigua And Barbuda",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "AG",
                "image" => "199.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 201,
                "name_ru" => "Боливия",
                "name_uz" => "Boliviya",
                "name_en" => "Bolivia",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "BO",
                "image" => "201.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 203,
                "name_ru" => "Пуэрто Рико",
                "name_uz" => "Puerto-Riko",
                "name_en" => "Puerto Rico",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "PR",
                "image" => "203.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 205,
                "name_ru" => "Буркина-Фасо",
                "name_uz" => "Burkina-Faso",
                "name_en" => "Burkina Faso",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "BF",
                "image" => "205.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 207,
                "name_ru" => "Эритрея",
                "name_uz" => "Eritreya",
                "name_en" => "Eritrea",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "ER",
                "image" => "207.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 209,
                "name_ru" => "Кения",
                "name_uz" => "Keniya",
                "name_en" => "Kenya",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "KE",
                "image" => "209.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 231,
                "name_ru" => "Мали",
                "name_uz" => "Mali",
                "name_en" => "Mali",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "ML",
                "image" => "231.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 211,
                "name_ru" => "Аруба",
                "name_uz" => "Aruba",
                "name_en" => "Aruba",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "AW",
                "image" => "211.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 213,
                "name_ru" => "Монголия",
                "name_uz" => "Mo'g'uliston",
                "name_en" => "Mongolia",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "MN",
                "image" => "213.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 215,
                "name_ru" => "Теркс и Кайкос",
                "name_uz" => "Turk va Kaykos",
                "name_en" => "Turks and Caicos Islands",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "TC",
                "image" => "215.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 217,
                "name_ru" => "Уганда",
                "name_uz" => "Uganda",
                "name_en" => "Uganda",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "UG",
                "image" => "217.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 219,
                "name_ru" => "Ботсвана",
                "name_uz" => "Botsvana",
                "name_en" => "Botswana",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "BW",
                "image" => "219.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 221,
                "name_ru" => "Белиз",
                "name_uz" => "Beliz",
                "name_en" => "Belize",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "BZ",
                "image" => "221.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 223,
                "name_ru" => "Никарагуа",
                "name_uz" => "Nikaragua",
                "name_en" => "Nicaragua",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "NI",
                "image" => "223.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 225,
                "name_ru" => "Зимбабве",
                "name_uz" => "Zimbabve",
                "name_en" => "Zimbabwe",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "ZW",
                "image" => "225.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 227,
                "name_ru" => "Барбадос",
                "name_uz" => "Barbados",
                "name_en" => "Barbados",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "BB",
                "image" => "227.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 229,
                "name_ru" => "Гамбия",
                "name_uz" => "Gambiya",
                "name_en" => "Gambia",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "GM",
                "image" => "229.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 233,
                "name_ru" => "Новая Каледония",
                "name_uz" => "Yangi Kaledoniya",
                "name_en" => "New Conia",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "NC",
                "image" => "233.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 235,
                "name_ru" => "Гвинея-Бисау",
                "name_uz" => "Gvineya-Bisau",
                "name_en" => "Guinea-Bissau",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "GW",
                "image" => "235.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 237,
                "name_ru" => "Сьерра-Леоне",
                "name_uz" => "Syerra-Leone",
                "name_en" => "Sierra Leone",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "SL",
                "image" => "237.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 239,
                "name_ru" => "Кабо-Верде",
                "name_uz" => "Kabo-Verde",
                "name_en" => "Cape Verde",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "CV",
                "image" => "239.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 241,
                "name_ru" => "Сенегал",
                "name_uz" => "Senegal",
                "name_en" => "Senegal",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "SN",
                "image" => "241.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 243,
                "name_ru" => "Бангладеш",
                "name_uz" => "Bangladesh",
                "name_en" => "Bangladesh",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "BD",
                "image" => "243.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 245,
                "name_ru" => "Кокосовые острова",
                "name_uz" => "Kokos orollari",
                "name_en" => "Cocos (Keeling) Islands",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "CC",
                "image" => "245.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 247,
                "name_ru" => "Доминика",
                "name_uz" => "Dominika",
                "name_en" => "Dominica",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "DM",
                "image" => "247.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 249,
                "name_ru" => "Тонга",
                "name_uz" => "Tonga",
                "name_en" => "Tonga",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "TO",
                "image" => "249.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 251,
                "name_ru" => "Фарерские острова",
                "name_uz" => "Farer orollari",
                "name_en" => "Faroe Islands",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "FO",
                "image" => "251.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 253,
                "name_ru" => "Сальвадор",
                "name_uz" => "Salvador",
                "name_en" => "El Salvador",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "SV",
                "image" => "253.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 255,
                "name_ru" => "Американское Самоа",
                "name_uz" => "Amerika samoasi",
                "name_en" => "American Samoa",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "AS",
                "image" => "255.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 257,
                "name_ru" => "Гибралтар",
                "name_uz" => "Gibraltar",
                "name_en" => "Gibraltar",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "GI",
                "image" => "257.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 259,
                "name_ru" => "Науру",
                "name_uz" => "Nauru",
                "name_en" => "Nauru",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "NR",
                "image" => "259.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 261,
                "name_ru" => "Американские Виргинские острова",
                "name_uz" => "AQSh Virjiniya orollari",
                "name_en" => "US Virgin Islands",
                "schengen" => false,
                "parent_id" => 50,
                "code" => "VI",
                "image" => "261.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 263,
                "name_ru" => "Того",
                "name_uz" => "Togo",
                "name_en" => "Togo",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "TG",
                "image" => "263.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 265,
                "name_ru" => "Фолклендские острова",
                "name_uz" => "Folklend orollari",
                "name_en" => "Falkland Islands",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "FK",
                "image" => "265.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 267,
                "name_ru" => "Сент-Китс и Невис",
                "name_uz" => "Sent-Kits va Nevis",
                "name_en" => "Saint Kitts and Nevis",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "KN",
                "image" => "267.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 269,
                "name_ru" => "Норфолк Айленд",
                "name_uz" => "Norfolk oroli",
                "name_en" => "Norfolk Island",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "NF",
                "image" => "269.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 271,
                "name_ru" => "Сан-Томе и Принсипи",
                "name_uz" => "San-Tome va Prinsipi",
                "name_en" => "Sao Tome and Principe",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "ST",
                "image" => "271.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 273,
                "name_ru" => "Северные Марианские острова",
                "name_uz" => "Shimoliy Marian orollari",
                "name_en" => "Northern Mariana Islands",
                "schengen" => false,
                "parent_id" => 50,
                "code" => "MP",
                "image" => "273.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 275,
                "name_ru" => "Реюньон",
                "name_uz" => "Reunion",
                "name_en" => "Reunion",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "RE",
                "image" => "275.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 276,
                "name_ru" => "Сент-Люсия",
                "name_uz" => "Sent-Lusiya",
                "name_en" => "Saint Lucia",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "LC",
                "image" => "276.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 277,
                "name_ru" => "Острова Уоллис и Футуна",
                "name_uz" => "Uollis va Futuna orollari",
                "name_en" => "Wallis and Futuna Islands",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "WF",
                "image" => "277.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 278,
                "name_ru" => "Остров Рождества",
                "name_uz" => "Rojdestvo oroli",
                "name_en" => "Christmas Island",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "CX",
                "image" => "278.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 152,
                "name_ru" => "Эстония",
                "name_uz" => "Estoniya",
                "name_en" => "Estonia",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "EE",
                "image" => "152.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 153,
                "name_ru" => "Эфиопия",
                "name_uz" => "Efiopiya",
                "name_en" => "Ethiopia",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "ET",
                "image" => "153.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 156,
                "name_ru" => "Ямайка",
                "name_uz" => "Yamayka",
                "name_en" => "Jamaica",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "JM",
                "image" => "156.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 61,
                "name_ru" => "Новая Зеландия",
                "name_uz" => "Yangi Zelandiya",
                "name_en" => "New Zealand",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "NZ",
                "image" => "61.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 157,
                "name_ru" => "Япония",
                "name_uz" => "Yaponiya",
                "name_en" => "Japan",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "JP",
                "image" => "157.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 159,
                "name_ru" => "Центральноафриканская Республика",
                "name_uz" => "Markaziy Afrika Respublikasi",
                "name_en" => "Central African Republic",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "CF",
                "image" => "159.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 148,
                "name_ru" => "Мальдивы",
                "name_uz" => "Maldiva",
                "name_en" => "Maldives",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "MV",
                "image" => "148.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 161,
                "name_ru" => "Норвегия",
                "name_uz" => "Norvegiya",
                "name_en" => "Norway",
                "schengen" => true,
                "parent_id" => 140,
                "code" => "NO",
                "image" => "161.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 164,
                "name_ru" => "Суринам",
                "name_uz" => "Surinam",
                "name_en" => "Suriname",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "SR",
                "image" => "164.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 154,
                "name_ru" => "ЮАР (Южно-Африканская Республика)",
                "name_uz" => "JAR (Janubiy Afrika Respublikasi)",
                "name_en" => "SAR (South African Republic)	",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "ZA",
                "image" => "154.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 166,
                "name_ru" => "Венесуэла",
                "name_uz" => "Venesuela",
                "name_en" => "Venezuela",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "VE",
                "image" => "166.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 168,
                "name_ru" => "Йемен",
                "name_uz" => "Yaman",
                "name_en" => "Yemen",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "YE",
                "image" => "168.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 172,
                "name_ru" => "Нигерия",
                "name_uz" => "Nigeriya",
                "name_en" => "Nigeria",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "NG",
                "image" => "172.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 210,
                "name_ru" => "Уругвай",
                "name_uz" => "Urugvay",
                "name_en" => "Uruguay",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "UY",
                "image" => "210.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 212,
                "name_ru" => "Вануату",
                "name_uz" => "Vanuatu",
                "name_en" => "Vanuatu",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "VU",
                "image" => "212.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 214,
                "name_ru" => "Ангилья",
                "name_uz" => "Angiliya",
                "name_en" => "Anguilla",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "AI",
                "image" => "214.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 174,
                "name_ru" => "Колумбия",
                "name_uz" => "Kolumbiya",
                "name_en" => "Colombia",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "CO",
                "image" => "174.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 176,
                "name_ru" => "Панама",
                "name_uz" => "Panama",
                "name_en" => "Panama",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "PA",
                "image" => "176.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 178,
                "name_ru" => "Чад",
                "name_uz" => "Chad",
                "name_en" => "Chad",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "TD",
                "image" => "178.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 180,
                "name_ru" => "Французская Полинезия",
                "name_uz" => "Frantsiya polineziyasi",
                "name_en" => "French Polynesia",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "PF",
                "image" => "180.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 216,
                "name_ru" => "Гаити",
                "name_uz" => "Gaitida",
                "name_en" => "Haiti",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "HT",
                "image" => "216.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 95,
                "name_ru" => "США (Соединённые Штаты Америки)",
                "name_uz" => "AQSH (Amerika Qo'shma shtatlari)",
                "name_en" => "USA (United States America)c",
                "schengen" => false,
                "parent_id" => 50,
                "code" => "US",
                "image" => "95.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 155,
                "name_ru" => "Южная Корея",
                "name_uz" => "Janubiy Koreya",
                "name_en" => "South Korea",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "KR",
                "image" => "155.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 145,
                "name_ru" => "Макао",
                "name_uz" => "Makao",
                "name_en" => "Macau",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "MO",
                "image" => "145.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 146,
                "name_ru" => "Македония",
                "name_uz" => "Makedoniya",
                "name_en" => "Macedonia",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "MK",
                "image" => "146.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 149,
                "name_ru" => "Мальта",
                "name_uz" => "Malta",
                "name_en" => "Malta",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "MT",
                "image" => "149.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 150,
                "name_ru" => "Марокко",
                "name_uz" => "Marokko",
                "name_en" => "Morocco",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "MA",
                "image" => "150.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 151,
                "name_ru" => "Мексика",
                "name_uz" => "Meksika",
                "name_en" => "Mexico",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "MX",
                "image" => "151.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 158,
                "name_ru" => "Узбекистан",
                "name_uz" => "Uzbekistan",
                "name_en" => "Uzbekistan",
                "schengen" => false,
                "parent_id" => 64,
                "code" => "UZ",
                "image" => null,
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 182,
                "name_ru" => "Гренландия",
                "name_uz" => "Grenlandiya",
                "name_en" => "Greenland",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "GL",
                "image" => "182.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 238,
                "name_ru" => "Руанда",
                "name_uz" => "Ruanda",
                "name_en" => "Rwanda",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "RW",
                "image" => "238.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 188,
                "name_ru" => "Маршалловы острова",
                "name_uz" => "Marshal orollari",
                "name_en" => "Marshall Islands",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "MH",
                "image" => "188.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 190,
                "name_ru" => "Острова Кука",
                "name_uz" => "Kuk orollari",
                "name_en" => "Cook Islands",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "CK",
                "image" => "190.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 192,
                "name_ru" => "Нигер",
                "name_uz" => "Niger",
                "name_en" => "Niger",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "NE",
                "image" => "192.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 194,
                "name_ru" => "Ливия",
                "name_uz" => "Liviya",
                "name_en" => "Libya",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "LY",
                "image" => "194.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 196,
                "name_ru" => "Сомали",
                "name_uz" => "Somali",
                "name_en" => "Somalia",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "SO",
                "image" => "196.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 198,
                "name_ru" => "Чили",
                "name_uz" => "Chili",
                "name_en" => "Chile",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "CL",
                "image" => "198.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 200,
                "name_ru" => "Лаос",
                "name_uz" => "Laos",
                "name_en" => "Laos",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "LA",
                "image" => "200.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 202,
                "name_ru" => "Фиджи",
                "name_uz" => "Fiji",
                "name_en" => "Fiji",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "FJ",
                "image" => "202.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 204,
                "name_ru" => "Танзания",
                "name_uz" => "Tanzaniya",
                "name_en" => "Tanzania",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "TZ",
                "image" => "204.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 206,
                "name_ru" => "Румыния",
                "name_uz" => "Ruminiya",
                "name_en" => "Romania",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "RO",
                "image" => "206.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 208,
                "name_ru" => "Багамские острова",
                "name_uz" => "Bagam orollari",
                "name_en" => "Bahamas",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "BS",
                "image" => "208.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 218,
                "name_ru" => "Коста-Рика",
                "name_uz" => "Kosta-Rika",
                "name_en" => "Costa Rica",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "CR",
                "image" => "218.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 220,
                "name_ru" => "Замбия",
                "name_uz" => "Zambiya",
                "name_en" => "Zambia",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "ZM",
                "image" => "220.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 222,
                "name_ru" => "Непал",
                "name_uz" => "Nepal",
                "name_en" => "Nepal",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "NP",
                "image" => "222.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 184,
                "name_ru" => "Гватемала",
                "name_uz" => "Gvatemala",
                "name_en" => "Guatemala",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "GT",
                "image" => "184.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 186,
                "name_ru" => "Гондурас",
                "name_uz" => "Gonduras",
                "name_en" => "Honduras",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "HN",
                "image" => "186.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 224,
                "name_ru" => "Ливан",
                "name_uz" => "Livan",
                "name_en" => "Lebanon",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "LB",
                "image" => "224.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 226,
                "name_ru" => "Камерун",
                "name_uz" => "Kamerun",
                "name_en" => "Cameroon",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "CM",
                "image" => "226.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 228,
                "name_ru" => "Ирак",
                "name_uz" => "Iroq",
                "name_en" => "Iraq",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "IQ",
                "image" => "228.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 230,
                "name_ru" => "Бурунди",
                "name_uz" => "Burundi",
                "name_en" => "Burundi",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "BI",
                "image" => "230.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 232,
                "name_ru" => "Малави",
                "name_uz" => "Malavi",
                "name_en" => "Malawi",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "MW",
                "image" => "232.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 234,
                "name_ru" => "Нидерландские Антильские острова",
                "name_uz" => "Gollandiya antil orollari",
                "name_en" => "Netherlands Antilles",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "AN",
                "image" => "234.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 236,
                "name_ru" => "Экваториальная Гвинея",
                "name_uz" => "Ekvatorial Gvineya",
                "name_en" => "Equatorial Guinea",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "GQ",
                "image" => "236.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 240,
                "name_ru" => "Бруней-Даруссалам",
                "name_uz" => "Bruney Darussalam",
                "name_en" => "Brunei Darussalam",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "BN",
                "image" => "240.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 242,
                "name_ru" => "Либерия",
                "name_uz" => "Liberiya",
                "name_en" => "Liberia",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "LR",
                "image" => "242.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 244,
                "name_ru" => "Французская Гвиана",
                "name_uz" => "Frantsiya gvianasi",
                "name_en" => "French Guiana",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "GF",
                "image" => "244.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 246,
                "name_ru" => "Бенин",
                "name_uz" => "Benin",
                "name_en" => "Benin",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "BJ",
                "image" => "246.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 248,
                "name_ru" => "Микронезия",
                "name_uz" => "Mikroneziya",
                "name_en" => "Federated States of Micronesia",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "FM",
                "image" => "248.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 250,
                "name_ru" => "Западная Сахара",
                "name_uz" => "G'arbiy Sahara",
                "name_en" => "Western Sahara",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "EH",
                "image" => "250.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 252,
                "name_ru" => "Мартиника",
                "name_uz" => "Martinika",
                "name_en" => "Martinique",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "MQ",
                "image" => "252.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 254,
                "name_ru" => "Сен-Пьер и Микелон",
                "name_uz" => "Sent-Per va Mikelon",
                "name_en" => "St. Pierre and Miquelon",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "PM",
                "image" => "254.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 256,
                "name_ru" => "Тувалу",
                "name_uz" => "Tuvalu",
                "name_en" => "Tuvalu",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "TV",
                "image" => "256.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 258,
                "name_ru" => "Гренада",
                "name_uz" => "Grenada",
                "name_en" => "Grenada",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "GD",
                "image" => "258.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 260,
                "name_ru" => "Ниуэ",
                "name_uz" => "Niue",
                "name_en" => "Niue",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "NU",
                "image" => "260.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 262,
                "name_ru" => "Лесото",
                "name_uz" => "Lesoto",
                "name_en" => "Lesotho",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "LS",
                "image" => "262.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 264,
                "name_ru" => "Монсеррат",
                "name_uz" => "Montserrat",
                "name_en" => "Montserrat",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "MS",
                "image" => "264.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 266,
                "name_ru" => "Свазиленд",
                "name_uz" => "Svazilend",
                "name_en" => "Swaziland",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "SZ",
                "image" => "266.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 268,
                "name_ru" => "Гуам",
                "name_uz" => "Guam",
                "name_en" => "Guam (USA)",
                "schengen" => false,
                "parent_id" => 50,
                "code" => "GU",
                "image" => "268.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 270,
                "name_ru" => "Бутан",
                "name_uz" => "Butan",
                "name_en" => "Bhutan",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "BT",
                "image" => "270.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 170,
                "name_ru" => "Кот д'Ивуар",
                "name_uz" => "Fil suyagi qirg'og'i",
                "name_en" => "Cote D'Ivoire",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "CI",
                "image" => "170.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 272,
                "name_ru" => "Тринидад и Тобаго",
                "name_uz" => "Trinidad va Tobago",
                "name_en" => "Trinidad And Tobago",
                "schengen" => false,
                "parent_id" => 35,
                "code" => "TT",
                "image" => "272.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 274,
                "name_ru" => "Палау",
                "name_uz" => "Palau",
                "name_en" => "Palau",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "PW",
                "image" => "274.png",
                "order" => null,
                "kapital_id" => null
            ],
            [
                "id" => 122,
                "name_ru" => "Италия",
                "name_uz" => "Italiya",
                "name_en" => "Italy",
                "schengen" => true,
                "parent_id" => 35,
                "code" => "IT",
                "image" => "122.png",
                "order" => null,
                "kapital_id" => 54
            ],
            [
                "id" => 86,
                "name_ru" => "Саудовская Аравия",
                "name_uz" => "Saudiya Arabistoni",
                "name_en" => "Saudi Arabia",
                "schengen" => false,
                "parent_id" => 51,
                "code" => "SA",
                "image" => "86.png",
                "order" => null,
                "kapital_id" => 72
            ],
            [
                "id" => 144,
                "name_ru" => "Эквадор",
                "name_uz" => "Ekvador",
                "name_en" => "Ecuador",
                "schengen" => false,
                "parent_id" => 49,
                "code" => "EC",
                "image" => "144.png",
                "order" => null,
                "kapital_id" => 188
            ],
            [
                "id" => 147,
                "name_ru" => "Малайзия",
                "name_uz" => "Malayziya",
                "name_en" => "Malaysia",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "MY",
                "image" => "147.png",
                "order" => null,
                "kapital_id" => 84
            ],
            [
                "id" => 63,
                "name_ru" => "ОАЭ (Арабские Эмираты)",
                "name_uz" => "BAA (Birlashgan Arab Amirligi)",
                "name_en" => "UAE (United Arab Emirates)",
                "schengen" => false,
                "parent_id" => 53,
                "code" => "AE",
                "image" => "63.png",
                "order" => null,
                "kapital_id" => 105
            ]
        ];

        $this->insertData('country', ["id","name_ru","name_uz","name_en","schengen","parent_id","code","image","order","kapital_id"], $data);
    }
}